#!/usr/bin/env python3
"""
Approach 1: Read PDF -> Convert to Markdown
Extracts text directly from PDF files and converts to markdown format.
"""

import sys
from pathlib import Path

try:
    import pdfplumber
except ImportError:
    print("Installing pdfplumber...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pdfplumber"])
    import pdfplumber

def extract_text_from_pdf(pdf_path):
    """Extract text from PDF preserving layout."""
    text_content = []
    
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, 1):
            # Extract text
            text = page.extract_text()
            if text:
                text_content.append(f"## Page {page_num}\n\n{text}\n")
            
            # Try to extract tables
            tables = page.extract_tables()
            if tables:
                for table_num, table in enumerate(tables, 1):
                    if table:
                        text_content.append(f"\n### Table {table_num} (Page {page_num})\n\n")
                        # Convert table to markdown format
                        markdown_table = convert_table_to_markdown(table)
                        text_content.append(markdown_table)
                        text_content.append("\n")
    
    return "\n".join(text_content)

def convert_table_to_markdown(table):
    """Convert a table (list of lists) to markdown format."""
    if not table:
        return ""
    
    markdown_lines = []
    
    # Header row
    if table:
        header = table[0]
        markdown_lines.append("| " + " | ".join(str(cell) if cell else "" for cell in header) + " |")
        markdown_lines.append("| " + " | ".join("---" for _ in header) + " |")
        
        # Data rows
        for row in table[1:]:
            markdown_lines.append("| " + " | ".join(str(cell) if cell else "" for cell in row) + " |")
    
    return "\n".join(markdown_lines)

def main():
    # PDF files to process
    pdf_files = [
        "Tenneroni_Victor_Resume.pdf",
        "Victor Tenneroni - 20251104 Deal Sheet.pdf"
    ]
    
    script_dir = Path(__file__).parent
    output_file = script_dir / "combined_markdown_approach1.md"
    
    all_content = []
    all_content.append("# PDF to Markdown Conversion - Approach 1 (Direct PDF Reading)\n\n")
    all_content.append("This document was generated by reading PDF files directly and extracting text.\n\n")
    all_content.append("---\n\n")
    
    for pdf_file in pdf_files:
        pdf_path = script_dir / pdf_file
        if not pdf_path.exists():
            print(f"Warning: {pdf_file} not found, skipping...")
            continue
        
        print(f"Processing {pdf_file}...")
        all_content.append(f"# {pdf_file}\n\n")
        
        try:
            content = extract_text_from_pdf(pdf_path)
            all_content.append(content)
            all_content.append("\n\n---\n\n")
        except Exception as e:
            print(f"Error processing {pdf_file}: {e}")
            all_content.append(f"Error: {str(e)}\n\n")
            all_content.append("---\n\n")
    
    # Write combined markdown file
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("".join(all_content))
    
    print(f"\nApproach 1 complete! Output saved to: {output_file}")

if __name__ == "__main__":
    main()
